{
 "title": "backend metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Backend Health Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"backend\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Request count Total",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_count_total{job=\"backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate by range",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(request_count_total{job=\"backend\"}[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "request latency seconds",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "rate(request_latency_seconds_bucket{instance=\"backend:5000\"}[$__rate_interval])",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Error",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "error_count_total{instance=\"backend:5000\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}